services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: books
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"   # host:container
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Library
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/books
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      JWT_SECRET_SECRET: +OC3w15btKLj250GX2rL6/bFJtaL+ebw8AkC0lyxm6A=
      JWT_SECRET_ACCESS_TOKEN_EXPIRATION: 3600000
      JWT_SECRET_REFRESH_TOKEN_EXPIRATION: 86400000
      

    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_GROK_KEY=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

volumes:
  db_data:

networks:
  app-network:
